### ISSUE TITLE
qjackctl forgets a connection when using pw-jack to use QjackCtl on Pipewire

### ISSUE THREAD

**Issue by Managor** [rncbc/qjackctl#119]
Demonstrative video: https://youtu.be/UK-zkwssDXY

I don't use JACK by itself so I don't know if this happens natively too. If this is a job for the Pipewire team, tell me so and I'll go pester them.

**Comment by rncbc** [comment]
and I don't use pipewire ... :) 

anyway, what exactly do you mean with "forget a connection" ? I must be missing something that is probably obvious for you, but the video is looking good from the pw side, i mean:)

**Comment by Managor** [comment]
By selecting the two audio blocks(not sure of the name) and pressing connect, I assume that the connection stays permanent any future connections would be automatically connected back to it. Similar to how they automatically connect to `HDA Intel PCH` in my video.

If that is not the way it's supposed to work, I would like to request that feature.

**Comment by rncbc** [comment]
no, they will never be permanent as far as firefox, as a JACK client, gets killed and restarted on every song, video and whatnot...

get a Patchbay profile running as active for that matter, but as said on the other reply, there are other solutions.

cheers
