### ISSUE TITLE
Feature request: client shaming when an xrun occurs

### ISSUE THREAD

**Issue by Gimmeapill** [rncbc/qjackctl#12]
Just an idea that could maybe ease troubleshooting and performance tuning in a multi application set up.
The xrun log sometimes points a a particular application "client X did not finish in time".
It would maybe be useful to reflect this in the GUI, or in the status windows.
Something like: out of N total xruns, client X caused Z xruns etc...
Or more generally improve the information about the source of xruns - as much as possible with the jack back end messages.

**Comment by rncbc** [comment]
those messages are issued by jackd and might vary on whether your running jack1 or jack2; 

far from that it is not being detected nor parsed by qjackctl. so no, this isn't going to happen any day soon.

**Comment by Gimmeapill** [comment]
Ok, got it. Any improvement must happen at jack level.
Thanks for the clarification.
