### ISSUE TITLE
All connections to a sink removed when removing one.

### ISSUE THREAD

**Issue by 38github** [rncbc/qjackctl#132]
Qjackctl 0.9.1
Qt 5.15.2
OpenSUSE Tumbleweed x86_64
X11

In Graph, there might be several programs connected to one sink/JACK application but when I selective the connections from one of these programs and delete them all the other application's connections to that sink also get removed. Only tested by removing pairs of connections.

**Comment by rncbc** [comment]
already fixed days ago on https://github.com/rncbc/qjackctl/commit/0e6baf0

**Comment by 38github** [comment]
I close this one since 0e6baf0 fixed it.
