### ISSUE TITLE
Graph View Menu Bar

### ISSUE THREAD

**Issue by gnzgg** [rncbc/qjackctl#141]
[ARCH] [i3wm]
Hi, this might be a result of me being silly and missing a button somewhere or something but I accidentally disabled the "Menu Bar" in Graph View and can't find a way to put it back

I have tried editing the config file (~/.config/rncbc/QjackCtl.conf) which does have this section:
```
[GraphView]
Menubar=false
```

But, as stated on your website, this doesn't do anything, since this config file is "recreated and rewritten everytime qjackctl is run."

Is there a "master" config file that can be edited ?

Obviously, a very simple workaround would be to reinstall QjackCtl but I thought this was worth pointing out as it might unnecessarily confuse users and can (probably) be fixed relatively easily (Enabling/Disabling the menu bar when pressing "Alt" for instance ?)

**Comment by rncbc** [comment]
unless your DE environment is tripping you there, Ctrl+M is the way to toggle the menu bar

**Comment by gnzgg** [comment]
welp i'm very dumb indeed ! Thanks for your answer :)
