### ISSUE TITLE
configure script does not use custom jack include directory to detect features

### ISSUE THREAD

**Issue by amurzeau** [rncbc/qjackctl#145]
When building qjackctl with a custom jack installation directory, autodetection of jack features (like metadata) fail because jack include path is not used to detect presence of jack headers.

This is a followup of https://github.com/jackaudio/jack2/issues/783.
The resulting qjackctl has no additional features as shown by this screenshot:
![image](https://user-images.githubusercontent.com/5435069/129932329-1125f754-7c6c-4c69-a130-7148a5984a73.png)

This issue occurs when building qjackctl as part of a jack release.

**Comment by amurzeau** [comment]
By looking the release build logs (https://github.com/jackaudio/jack2-releases/runs/3099787172), I see this:
```
2021-07-19T01:32:23.2518699Z checking jack/metadata.h usability... no
2021-07-19T01:32:23.2661478Z checking jack/metadata.h presence... no
2021-07-19T01:32:23.2662364Z checking for jack/metadata.h... no
2021-07-19T01:32:23.2663168Z configure: WARNING: *** jack/metadata.h file not found.
2021-07-19T01:32:23.2664151Z configure: WARNING: *** JACK 0.124.1 or later may be required.
2021-07-19T01:32:23.2664999Z configure: WARNING: *** JACK metadata support will be disabled.
```

In configure.ac script, jack include path is added to a variable called $ac_cflags:
```bash
# Check for JACK libraries.
[...]
   ac_cflags="$ac_cflags $JACK_CFLAGS"
   ac_libs="$ac_libs $JACK_LIBS"
```

Later, features (like metadata) are detected using `AC_CHECK_HEADER`:
```bash
AC_CHECK_HEADER(jack/metadata.h, [ac_jack_metadata="yes"], [ac_jack_metadata="no"])
```

But at this time, autoconf does not use $ac_cflags, as seen in config.log, so jack's headers are not found by `AC_CHECK_HEADER`:
```
configure:6323: checking jack/metadata.h usability
configure:6323: i686-w64-mingw32-g++ -c -std=c++17 -O2 -pipe -I/home/runner/PawPawBuilds/targets/win32/include  -mtune=generic -msse -msse2 -ffast-math -fPIC -DPIC -DNDEBUG -D_FORTIFY_SOURCE=2 -fdata-sections -ffunction-sections -fno-common -fstack-protector -fvisibility=hidden -mfpmath=sse -DFLUIDSYNTH_NOT_A_DLL -DPTW32_STATIC_LIB -mstackrealign -DHAVE_MIXED_SIZE_ADDRESSING -fvisibility-inlines-hidden  -I/home/runner/PawPawBuilds/targets/win32/include/qt5 -fPIC  conftest.cpp >&5
conftest.cpp:65:10: fatal error: jack/metadata.h: No such file or directory
   65 | #include <jack/metadata.h>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
```

----

I don't know autoconf well, but apparently it is possible to just update $CFLAGS instead of using a custom variable.

**Comment by rncbc** [comment]
autoconf is being phased out... cmake is the official build system now.

**Comment by amurzeau** [comment]
Closing now that it is fixed with recent changes. I've remade a jack2-release build test with cmake to ensure everything is fine (don't mind how I'm patching qjackctl in jack2-release :))
https://github.com/amurzeau/jack2-releases/actions/runs/1153941131
