### ISSUE TITLE
[MacOS] Unable to specify input/output devices with spaces

### ISSUE THREAD

**Issue by VladV** [rncbc/qjackctl#156]
I'm trying to configure separate input and output devices – that is, `-C` and `-P` options of `jackd`.

Dropdowns in Settings/Advanced are inactive for some reason, so I can't use them.

Specifying `-C <device name>` as server suffix doesn't work either, because the name contains spaces (`jackd -l` lists it as `Device ID = '46' name = 'USB Digital Audio', internal name = 'AppleUSBAudioEngine:MACROSILICON:USB Video:14413000:3' (to be used as -C, -P, or -d parameter)`).
The name gets split by spaces, so only `AppleUSBAudioEngine:MACROSILICON:USB` is fed to `jackd`, so it fails to resolve the device (if I give the name in quotes to `jackd` in a shell, it works fine, so the problem is specific to QjackCtl).

<img width="668" alt="image" src="https://user-images.githubusercontent.com/184503/131573884-557f1a3f-fc36-4a66-8cc8-557bbc58aede.png">

QjackCtl 0.9.4, MacOS Catalina 10.15.7 (Intel).

**Comment by rncbc** [comment]
have no experience on macosx though I vaguely remember the "coreaudio" back-end do not allow for separate capture (`-C`) and playback devices (`-P`); maybe things have evolved since a decade or so, IDK. I don't touch that platform anyhow; someone else who can may chime in perhaps...

suggestion: use quotes (`'` or `"`) _explicitly_ on the device name entry fields.

**Comment by VladV** [comment]
As I said, jackd by itself works fine, so coreaudio seems not to be a problem now.

I tried using quotes to no avail - as far as I can see from the code, arguments in "server suffix" are just split by spaces, with no respect for quoting. If you implement more elaborate parsing of this field, that might help - probably, would be useful for other platforms too (not sure whether spaces in device names are legal elsewhere).

**Comment by rncbc** [comment]
PR's are welcome!

**Comment by kreisys** [comment]
I don't actually swim in C++ or Qt but I seem to have fixed it by changing a handful of lines. Here's the PR: https://github.com/rncbc/qjackctl/pull/179
