### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by amurzeau** [rncbc/qjackctl#158]
Hi,

What do you think about doing a new release ?
There will be a new release of Jack2 on 15/10 and I will try to have metadata working with the bundled qjackctl by switching from autotools to cmake in the Jack2 installer build.

If you want I can also make a PR about github actions to automatically create a new github release with the generated binaries when there is a tag.

**Comment by rncbc** [comment]
ok. i'll make the translators update call soon and after a week or so it's ready for new release (qjackctl_0_9_5)
thanks

**Comment by rncbc** [comment]
new release (v0.9.5) is very nigh... are you ready? 

:)

**Comment by amurzeau** [comment]
yes ready :)

**Comment by rncbc** [comment]
new release (v0.9.5) is out!

**Comment by amurzeau** [comment]
in the process to integrate it in jack installer :)
