### ISSUE TITLE
Can we have this as an option to remove GLASS EFFECT again? ( IN WINDOWS 10) 

### ISSUE THREAD

**Issue by boscobothelo** [rncbc/qjackctl#159]
I dont know where is the configuration file placed in windows. PLEASE HELP !
![image](https://user-images.githubusercontent.com/91069058/134006155-76a1a49d-ed78-4459-a680-16b94ca1fb41.png)

as in linux the location is : 
(~/.config/rncbc.org/QjackCtl.conf):

updating this would remove the glass effect...

[Options]
DisplayEffect=false

HOW CAN I DO THE SAME IN WINDOWS 10. PLEASE TELL ME THE LOCATION OF CONFIGURATION FILE

**Comment by rncbc** [comment]
in windows it should appear be on the registry; use regedit(32) for that matter, thanks

and no, that option won't see the light anymore :)
cheers

**Comment by boscobothelo** [comment]
THANK YOU VERY MUCH ! @rncbc 


I found the option at :- 
Computer\HKEY_CURRENT_USER\SOFTWARE\rncbc.org\QjackCtl\Options
![QjackCtl](https://user-images.githubusercontent.com/91069058/134048029-6032a648-5a2f-4888-a7a0-a45aad7d6281.png)

**Comment by boscobothelo** [comment]
THANK YOU VERY MUCH ! @rncbc

I found the option at :-
Computer\HKEY_CURRENT_USER\SOFTWARE\rncbc.org\QjackCtl\Options
![QjackCtl2](https://user-images.githubusercontent.com/91069058/134048532-2a96a478-97d2-40b1-897c-38223dae5504.png)

**Comment by boscobothelo** [comment]
THANK YOU VERY MUCH! @rncbc

I found the option at:-
Computer\HKEY_CURRENT_USER\SOFTWARE\rncbc.org\QjackCtl\Options
![QjackCtl2](https://user-images.githubusercontent.com/91069058/134050148-0e0e4513-2194-4b49-9385-d24483efc0b8.png)
