### ISSUE TITLE
qjackctl 0.9.5 build issue

### ISSUE THREAD

**Issue by chenrui333** [rncbc/qjackctl#161]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build error</summary>

```
qjackctlGraph.cpp:1130:28: error: call to deleted constructor of 'const QPainterPathStroker'
        const QPainterPathStroker stroker
                                  ^
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/runs/3848887022
relates to Homebrew/homebrew-core#86984

**Comment by rncbc** [comment]
maybe fixed by 86c482f , develop branch.

**Comment by chenrui333** [comment]
@rncbc sorry about the delay, the patch works for me on my m1 machine (gonna run the full PR build), thanks for the fix!

**Comment by chenrui333** [comment]
As [my PR](https://github.com/Homebrew/homebrew-core/pull/86984) got merged, closing this issue now.

@rncbc thanks for the patch!
