### ISSUE TITLE
qjackctl various bugs and issues with pipewire

### ISSUE THREAD

**Issue by dreamcat4** [rncbc/qjackctl#163]
Hello!
As somebody who has been uing qjackctl with jack natively for a long time. This is a useful tool for its patchbay and session manager etc.

However since upgrading to pipewire, (which is fantastic BTW and solves all my previous performance issues with jack)....

Well there have been some bugs. At first I though this was problems with pipewire. Because it is a new software. However after some months and further examination. It has been found to only occur wich qjackctl running.

That is to say: if i have other jack apps running. They work fine. And so does qjackctl work fine too. At least to begin with. However over time during a session bugs appear later on. And there are a variety of different bugs.

The conclusion is that either my configuration in qjackctl is wrong. For example because some setting in there.

Or that there are issue with interoperability of these combination of 2 different software. Where it isnt my own config but some other problem.

Either way I just wanted to let you know. And link the tracking issue over in pipewire gitlab. So that people are aware of this matters. In case it happens to anybody else.

You probably dont need to take much action if you consider this to be a legacy software now. Or if you do not feel that people should be using qjackctl with pipewire specificaly together. But what I would say is that it can help users (like me!) to debug their problem to be aware of this. So maybe it could be written somewhere appropriately in the user documentation for both projects. To let other people know that more clearly. Many thanks.

Here is link to tracking issue (on pipewire project):

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1703#note_1156898

**Comment by rncbc** [comment]
what happens if you don't use pw at all and use jack natively, not the pipewire-libjack substitution? 

I bet it should work ou fine then... which may be telling you that the "zombie-effect" is one of pipewire-jack to blame, I guess.

as an alternative to qjackctl to manage pw connections, you may now try with yours truly spin-off qpwgraph specially dedicated to pw though:
https://gitlab.pipewire.org/rncbc/qpwgraph

test && tell
cheers

**Comment by dreamcat4** [comment]
absolutely correct.

before moving to pipewire, with only jackd. then there were never any such problem. it is specific to running both together (with libjackd replaced by the pipewire version of libjeck).

thanks so much for letting me know about the new `qpwgraph` tool! as was not aware of it previouly. will try it out soon
