### ISSUE TITLE
How to turn off glaring reflection on timer display

### ISSUE THREAD

**Issue by Sciss** [rncbc/qjackctl#167]
Hi there, thanks for QJackCtl. I recently upgraded from Debian 10 to 11, and this includes a new version of QJackCtl (it's 0.9.1 now). I used to turn off the glaring reflection on the status / timer display in the main window that makes it difficult to read and seems like an idiosyncrasy to me:

![qjackctl-reflecting-display](https://user-images.githubusercontent.com/131300/146696017-ad1973d7-7df9-404b-bdf2-f2538ddf7def.png)

Somehow, I can no longer find the Setup item to turn this off. I think it was in the Options or Misc tab? Thanks

**Comment by rncbc** [comment]
the option has vanished from the GUI but still accessible from the conf file.
`~/.config/rncbc.org/QjackCtl.conf`
```
[Options]
DisplayEffect=false
```

**Comment by Sciss** [comment]
Ok, thanks!
