### ISSUE TITLE
Can't switch presets in HEAD

### ISSUE THREAD

**Issue by KottV** [rncbc/qjackctl#168]
Hi,
I use qjackctl 0.9.5.16git.8404ab from your openSUSE TW repo
I have some profiles, `kv_dummy` and `Gina` for example. Whenever I select `Gina` preset qjackctl starts jack with dummy preset option.
Even if I delete `kv_dummy` preset it still tries to start it.

I deleted `OldPreset=kv_dummy` in `Presets` section of `QjackCtl.conf` then recreated that prest, now it seems to allows to switch between presets.

**Comment by rncbc** [comment]
maybe fixed in qjackctl 0.9.5.17git.[c55522](https://github.com/rncbc/qjackctl/commit/c555220)

thanks for the heads up && cheers

**Comment by KottV** [comment]
Yep, It's fixed. Thank You!

**Comment by KottV** [comment]
I run to that (or similar) problem again.
Had to set in `QjackCtl.conf`:
```
DefPreset=kv_Gina_48
```

Otherwise, it starts server with "default".

**Comment by KottV** [comment]
version 0.9.6.17git.324ad6

**Comment by rncbc** [comment]
beware: if qjackctl is working in pure jack-client mode ("Active" is shown on the main display) presets have no use whatsoever.

qjackctl presets are only meaningful for when the jackd(bus) is started under qjackctl premises.

make sure you're not falling into the "running as client" scenario, which is *always* the case when under pipewire, mind you.
cheers

**Comment by KottV** [comment]
I'm starting jackd by qjackctl. Well, I can't reproduce it anymore, even with "broken" conf. Close it :)
