### ISSUE TITLE
Problems with a2jmidid

### ISSUE THREAD

**Issue by oscarsantis** [rncbc/qjackctl#185]
In options panel I have enabled as a script after starting the server jack "a2jmidid -e". But when I start the server it freezes

**Comment by oscarsantis** [comment]
Debian 11
Kernel 5.15

**Comment by rncbc** [comment]
you have to run a2jmidid in the background: append an ampersand (`&`) to end of the line
eg. `a2jmidid -e &`

**Comment by oscarsantis** [comment]
Perfect, now runs fine.
Thanks
