### ISSUE TITLE
symbol lookup error:

### ISSUE THREAD

**Issue by reahari** [rncbc/qjackctl#191]
Trying to launch qjackctl and it crashes with the following error when launched from the terminal
```
qjackctl: symbol lookup error: /lib/x86_64-linux-gnu/libbrotlidec.so.1: undefined symbol: _kBrotliPrefixCodeRanges
```
Installed on Ubuntu 22.04 via ppa https://launchpad.net/~rncbc/+archive/ubuntu/apps-jammy

**Comment by rncbc** [comment]
probably due a recent update to the `brotli` package which is not a direct build-dependency to qjackctl whatsoever
will try to bump a new build on the ppa and see if it fixes the issue.
thanks

**Comment by reahari** [comment]
I got an update in the ppa and that did not fix it. I manually cpiled brotli and that fixed things
