### ISSUE TITLE
qjackctl configure fails with Qt 5.7

### ISSUE THREAD

**Issue by a17r** [rncbc/qjackctl#20]
```
checking for qmake-qt5... no
checking for qmake... /usr/lib64/qt5/bin/../bin/qmake
checking for qmake... (cached) /usr/lib64/qt5/bin/../bin/qmake
checking for Qt library version >= 5.1... no; Qt 5.1 or greater is required
```

The solution would be passing -std=c++11 to CXXFLAGS.

**Comment by rncbc** [comment]
it's more about the compiler version (g++ --version?) you're using and to which it recognizes and defaults to a >= c++11 anyway. for example, for g++ >= 6.1, (the one in use upstream and also recommended for Qt >= 5.7.0), you won't need to pass CXXFLAGS="-std=c++11" as suggested.

hth.
cheers

**Comment by a17r** [comment]
Yes, if you use GCC-6 there is no problem, but with GCC-5.4.0 it will already fail to configure. -std=c++11 should solve configure going back to GCC 4.9

**Comment by vberthiaume** [comment]
I'm getting this very same error. I got Qt 5.7 and GCC-6.
```
~/Documents/git/qjackctl$ ./configure 
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
./configure: line 3866: PKG_PROG_PKG_CONFIG: command not found
checking for g++ major version... 6
checking for qmake-qt5... no
checking for qmake... /Users/nicolai/Qt/5.7/clang_64/bin/qmake
checking for Qt major version... 5
checking for Qt install path... /Users/nicolai/Qt/5.7/clang_64/bin
checking for qmake... (cached) /Users/nicolai/Qt/5.7/clang_64/bin/qmake
checking for Qt install headers... /Users/nicolai/Qt/5.7/clang_64/include
checking for Qt install libraries... /Users/nicolai/Qt/5.7/clang_64/lib
checking for Qt library version >= 5.1... no; Qt 5.1 or greater is required
```

**Comment by rncbc** [comment]
On 11/25/2016 02:37 PM, Vincent Berthiaume wrote:
> I'm getting this very same error. I got Qt 5.7 and GCC-6.
> 
> |~/Documents/git/qjackctl$ ./configure sed: illegal option -- r usage:
> sed script [-Ealn] [-i extension] [file ...] sed [-Ealn] [-i extension]
> [-e script] ... 
<snip>
> /Users/nicolai/Qt/5.7/clang_64/bin checking for qmake... (cached)
> /Users/nicolai/Qt/5.7/clang_64/bin/qmake checking for Qt install
> headers... /Users/nicolai/Qt/5.7/clang_64/include checking for Qt
> install libraries... /Users/nicolai/Qt/5.7/clang_64/lib checking for Qt
> library version >= 5.1... no; Qt 5.1 or greater is required |
> 

looks like you're not having the configure script setup properly, or
else, you're somewhat targeting clang and not gcc/g++

go figure
-- 
rncbc aka. Rui Nuno Capela
rncbc@rncbc.org

**Comment by a17r** [comment]
Whatever Qt may recommend, there is no good reason to have this package fail to build by default with pre-GCC-6. Upstream hasn't fixed the world to build with GCC-6 yet, and there's even build issues with vanilla Qt-5.7.0 itself.

**Comment by vberthiaume** [comment]
alright, I finally got qt to be recognized by doing this:

```
brew tap homebrew/versions
brew install qt55
brew link --force qt55
```

I am now getting this error when doing `./configure` :

```
./configure: line 4615: syntax error near unexpected token `JACK,'
./configure: line 4615: `PKG_CHECK_MODULES(JACK, jack >= 0.100.0, ac_jack_lib="yes", ac_jack_lib="no")'
```

**Comment by rncbc** [comment]
On 11/28/2016 04:55 PM, Vincent Berthiaume wrote:
> alright, I finally got qt to be recognized by doing this:
> 
> |brew tap homebrew/versions brew install qt55 brew link --force qt55 |
> 
> I am now getting this error when doing |./configure| :
> 
> |./configure: line 4615: syntax error near unexpected token `JACK,'
> ./configure: line 4615: `PKG_CHECK_MODULES(JACK, jack >= 0.100.0,
> ac_jack_lib="yes", ac_jack_lib="no")' |
> 

you need pkg-config (or pkgconfig depending on your distro packaging)
installed also (it usually is when you prepare and install a GNU
development environment and toolchain.

hth
-- 
rncbc aka. Rui Nuno Capela
rncbc@rncbc.org

**Comment by vberthiaume** [comment]
alright, sorry for bombarding this issue, just not sure if this stuff is all related or not (tell me if you want me to create another one). I was able to install pkg-config correctly and run the configure script. However when I make, i get this:

```
cd src/ && ( test -e Makefile || /usr/local/bin/qmake /Users/nicolai/Documents/git/qjackctl/src/src.pro -o Makefile ) && /Applications/Xcode.app/Contents/Developer/usr/bin/make -f Makefile 
Project ERROR: Unknown module(s) in QT: dbus
make[1]: *** [sub-src-make_first] Error 3
make: *** [src/qjackctl] Error 2
```
Is [this the required dbus](https://www.freedesktop.org/wiki/Software/dbus/#index5h1)? Or is this error referring to jackdbus, or something else?

thank you so much for your help!

**Comment by rncbc** [comment]
> Is this the required dbus? Or is this error referring to jackdbus, or something else?

you probably need to install Qt5Dbus (or QtDbus on Qt4) that usually comes as an additional package.

or else, rerun with `./configure --disable-dbus` ...

hth.
