### ISSUE TITLE
QPainter messages 

### ISSUE THREAD

**Issue by albmef** [rncbc/qjackctl#204]
hi i get the message windows filled with QPainter messages over time:
"
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::begin: Paint device returned engine == 0, type: 2
QPainter::begin: Paint device returned engine == 0, type: 2
...
"

they are not related to audio, and they make the reading more difficult in case of XRUN or other jack issue.
i think these messages are not relevant for most jack users imho so,
could you please remove them ? or in the meantime, give us a fix for making them not to appear in the message window ?

thanks for all you work and for your support
best regards,
AM

**Comment by rncbc** [comment]
what qjackctl version (`qjackctl -v`), package and respective origin?

you might have a way too old package or else, not well suited for your desktop environment.

**Comment by albmef** [comment]
so,
i use ubuntu 23.10 aarch64 linux 6.5.0-1011 raspi   with GNOME 3 desktop
qjackctl 0.9.12  with QT 6.4.2
i installed it from the official ubuntu apt repo
i have lots of QPainter messages when i have XRUNS. they seem associated .
at first glance, when all is stable i have no XRUNS and no Qpainters messages

AM

**Comment by rncbc** [comment]
can't help you there, sorry

though, you can just try turning off Options > Capture standard output.

**Comment by albmef** [comment]
my systemd message log is filled with QPainter messages from JACK at a rate of about 15 messages per seconds.
any idea ? i think you should deactivate in the QT debugging messages in qjackctl. this will wear my pi4 sdcard out isn't it ?
AM

**Comment by rncbc** [comment]
these are not qjackctl messages per se; i dunno where they come from, maybe it's from the (your) Qt build in particular on your side or distro.

ps. jftr. they don't ever appear on any of my test cases.

**Comment by albmef** [comment]
that what i'm suspecting too. maybe the QT lib is too chatty. thanks for your support
