### ISSUE TITLE
where is the configure script?

### ISSUE THREAD

**Issue by vberthiaume** [rncbc/qjackctl#21]
Potentially a n00b question, but are we supposed to generate the configure script ourselves from configure.ac?

**Comment by vberthiaume** [comment]
ok, yes, you're supposed to, simply by doing

`autoconf`

if you don't have autoconf, install [brew](http://brew.sh/), then 

`brew install autoconf`

**Comment by rncbc** [comment]
`make -f Makefile.git`
or
`./autogen.sh`
will do the trick.

**Comment by vberthiaume** [comment]
those commands are supposed to create a configure script? I only get this: 
```
~/Documents/git/qjackctl$ make -f Makefile.git 
make: Nothing to be done for `all'.
~/Documents/git/qjackctl$ ./autogen.sh 
make: Nothing to be done for `all'.
```

**Comment by rncbc** [comment]
because you already done the `autoconf` step before.
try this:
```
make -f Makefile.git clean
make -f Makefile.git
```
or
```
./autogen.sh clean
./autogen.sh
```
nb. both command sequences are equivalent.
hth.

**Comment by vberthiaume** [comment]
right, just saw the `make -f Makefile.git` part, sorry! This does create a configure script, after making sure to install automake with `brew install automake`
