### ISSUE TITLE
Replace WIN32 with _WIN32

### ISSUE THREAD

**Issue by kmatheussen** [rncbc/qjackctl#25]
Hi, WIN32 is not always defined:
https://sourceforge.net/p/mingw-w64/mailman/message/31850993/

For instance, if compiling with --std=c++11, WIN32 is not defined. On the other hannd, --std=gnuc++11 WILL define WIN32. So it's a bit random.

_WIN32 is always safe to use though.

Here's a commit you can cherry pick:
https://github.com/kmatheussen/qjackctl/commit/1b3d8a1dcd2947c33160a1f48ea822b3fd5f8940

Thank you.

**Comment by rncbc** [comment]
applied as commit https://github.com/rncbc/qjackctl/commit/d0c2e4a0

thanks
