### ISSUE TITLE
Would displaying both sampling rates avoid confusion?

### ISSUE THREAD

**Issue by Redsandro** [rncbc/qjackctl#29]
I'm new to jack.

The window shows the configured sampling rate on the window (top-right of the display "48000 Hz"):

![image](https://user-images.githubusercontent.com/1702193/37652454-db092b12-2c3b-11e8-94a0-673efefffb87.png)
(Don't mind the mix of resolutions - it's reported in #28)

However, `jack` might ignore this for one reason or another, and the _messages_ window seems to show this:

> Starting jack server...
> JACK server starting in realtime mode with priority 10
> self-connect-mode is "Don't restrict self connect requests"
> Acquired audio card Audio1
> Acquired audio card Audio0
> creating alsa driver ... hw:PCH,0|hw:ToneLabST,0|128|3|__44100__|0|0|nomon|swmeter|-|16bit
> configuring for __44100Hz__, period = 128 frames (2.9 ms), buffer = 3 periods

This is confusing because you'll get errors like: 

> __ERROR: playback and capture sample rates do not match (48000 vs. 44100)__

And it's confusing because you think the window shows you what frequency is being used (48000Hz) while actually 44100Hz is being used and the window simply seems to show what you wrote in the settings. This would make the display more of a wishful thinking rather than an actual frequency gauge

Again, I might have interpreted this all wrong. But since I'm new to jack, I could be considered an UX tester and I'm confused. Perhaps the Window display can show both the playback and capture sample rates with a nice little alert indicator showing which hardware device is "in the wrong", because in settings you can only specify one rate, not separate rates for both capture and playback.

**Comment by rncbc** [comment]
sample is set and reported by the JACK sub-system; it is not a qjackctl issue.

**Comment by Redsandro** [comment]
@rncbc Looks like I made a wrong assumption. I'm just trying to get this setup to work. Could you help me out and point me in the right direction?

**Comment by rncbc** [comment]
1. your sound card probably only runs on 48k and that's the sample-rate that jack runs at all;
2. jack does not do sample-rate conversion so all clients run at nominal sample-rate (48k in your case).
3. if you want to playback correctly audio files that are originally at 44k1 make sure your audio player does sample-rate conversion accordingly (upsampling 44k1 to 48k).
