### ISSUE TITLE
Cannot use system tray menu on Ubuntu 18.04

### ISSUE THREAD

**Issue by jpleau** [rncbc/qjackctl#30]
Hi.

On Ubuntu 18.04 (GNOME), qjackctl works except that the system tray menu does not.

What happens: I launch qjackctl, I see the app opening, and the system tray menu appears where my mouse currently is. I then have to press Escape to make it disappear.

Right clicking on the qjackctl icon in the panel doesn't bring up the usual menu. I have to double click the icon to have the window appear.

qjackctl version in ubuntu is 0.4.5, but I backported 0.5.0 from debian unstable and I get the same issue.

I can post screenshots / screencasts if needed if you have trouble understand what I tried to describe above :)

**Comment by rncbc** [comment]
yes it's a known issue on Gnome3 and also similar to Unity from previous Ubuntu's, etc.

this applies to all Qt5 application system-tray icons, not only QjackCtl, so sorry.

please don't rely on the system-tray icon on those environments for which it has been so to speak, banned :)

cheers

**Comment by jpleau** [comment]
Ok I wasn't aware of that sorry.

Last time I used gnome or ubuntu was at version 6.06 back in 2006, it changed quite a bit.

**Comment by stuaxo** [comment]
There is an extension that integrates Ubuntu AppIndicators and KStatusNotifierItems (KDE's blessed successor of the systray) into GNOME Shell.
If qjackctl ever moves to KStatusNotifierItem it would start working.

https://github.com/ubuntu/gnome-shell-extension-appindicator
