### ISSUE TITLE
pt_BR translation

### ISSUE THREAD

**Issue by heit0r** [rncbc/qjackctl#37]
Hello Qjackctl team,

How can i translate it to brazilian portuguese or help doing?

Obrigado.

**Comment by rncbc** [comment]
easy, on your own forked/cloned/branched working copy:

edit and add this line to src/src.pro (under TRANSLATIONS += ...)

    translations/qjackctl_pt.ts \

from the source root run `lupdate qjackctl.pro` and there you should fire `linguist` and open the just created source file src/translations/qjackctl_pt.ts.

also add yourself to the TRANSLATORS file and then, whenever finished with linguist, propose a merge request

cheers

**Comment by heit0r** [comment]
Thank you! I'll comment here when i feel that i finished it.

**Comment by heit0r** [comment]
Thanks! I founded the translation files on the path you gave. I'll comment here when i finish.
