### ISSUE TITLE
Issue with QjackCtl 0.5.2

### ISSUE THREAD

**Issue by sub26nico** [rncbc/qjackctl#38]
I have issue with QjackCtl with preset having () in the name. 
Ardour doesn't have sound output if the name of preset in QjackCtl is (default), 
it's working if I erase the () in the preset name, it wors with 'default'. 
Reaper (native linux version) give error message too (if thre is () ). 
it was working fine with QjackCtl 5.0.0.

**Comment by rncbc** [comment]
are you with the French (fr) translation? this last one was indeed with a translation mistake (a string that should have never been translated).

if that's the case, to work around that please run v0.5.2 as follows:

`LANG=C qjackctl`

the fr translation has been fixed on git head already.

thanks

**Comment by sub26nico** [comment]
with QjackCtl in English, Ardour and Reaper works fine. Strange thing, I read error with reaper 
and Qjack in english forums (https://forum.cockos.com/showpost.php?p=1994484&postcount=523), 
and it was the same here. Maybe this reaper user have non english system). 
@rncbc : do you want I close here ?

**Comment by rncbc** [comment]
thanks. closing now.

**Comment by trebmuh** [comment]
@rncbc I added 2 translator's comment. See #38 .

**Comment by rdoursenaud** [comment]
@rncbc 
> are you with the French (fr) translation? this last one was indeed with a translation mistake (a string that should have never been translated).

If the string shall not be translated, the proper fix is to mark it as such in the Designer file by setting the `string` tag `notr` attribute to `true`.
This way, it won't even appear in the translation file and fix the issue for all languages.
Yes, I'm deflecting the blame :p
