### ISSUE TITLE
Make fails with "unknown modules dbus x11extras"

### ISSUE THREAD

**Issue by arun-gurung** [rncbc/qjackctl#41]
Otherwise, configure script runs fine.

[root@air qjackctl-git]# make
make[1]: Entering directory `/tmp/qjackctl-git'
cd src/ && ( test -e Makefile || /opt/Qt/5.11.1/android_x86/bin/qmake -o Makefile /tmp/qjackctl-git/src/src.pro ) && make -f Makefile 
Project ERROR: Unknown module(s) in QT: dbus x11extras
make[1]: *** [sub-src-make_first] Error 3
make[1]: Leaving directory `/tmp/qjackctl-git'
make: *** [src/qjackctl] Error 2

**Comment by rncbc** [comment]
you seem to building for android... where x11extras is not available for sure.

try with `./configure --disable-xunique --with-qt=/opt/Qt/5.11.1/android_x86 `...

**Comment by arun-gurung** [comment]
Thanks, I also had to set --disalbe-dbus to get past that error. But now it complains about missing jack.h Please help.

[root@air qjackctl-git]# make
make[1]: Entering directory `/tmp/qjackctl-git'
cd src/ && ( test -e Makefile || /opt/Qt/5.11.1/android_x86/bin/qmake -o Makefile /tmp/qjackctl-git/src/src.pro ) && make -f Makefile 
make[2]: Entering directory `/tmp/qjackctl-git/src'
/opt/Qt/5.11.1/android_x86/bin/qmake -o Makefile src.pro
make[2]: Leaving directory `/tmp/qjackctl-git/src'
make[2]: Entering directory `/tmp/qjackctl-git/src'
/opt/Qt/5.11.1/android_x86/bin/uic qjackctlPatchbayForm.ui -o .ui/ui_qjackctlPatchbayForm.h
/tmp/android-ndk-r17b/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-g++ -c -D__ANDROID_API__=16 --sysroot=/tmp/android-ndk-r17b/sysroot -isystem /tmp/android-ndk-r17b/sysroot/usr/include/i686-linux-android -isystem /tmp/android-ndk-r17b/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem /tmp/android-ndk-r17b/sources/cxx-stl/gnu-libstdc++/4.9/libs/x86/include -fstack-protector-strong -DANDROID /usr/include/jack -I/usr/include/alsa -pthread -I/usr/include/alsa -O2 -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -I/opt/Qt/5.11.1/android_x86/include -I/opt/Qt/5.11.1/android_x86/include/QtWidgets -I/opt/Qt/5.11.1/android_x86/include/QtGui -I/opt/Qt/5.11.1/android_x86/include/QtXml -I/opt/Qt/5.11.1/android_x86/include/QtCore -I.moc -I.ui -I/opt/Qt/5.11.1/android_x86/mkspecs/android-g++ -o .obj/qjackctl.o qjackctl.cpp
In file included from qjackctl.cpp:24:0:
qjackctlMainForm.h:34:23: fatal error: jack/jack.h: No such file or directory
 #include <jack/jack.h>

**Comment by rncbc** [comment]
you shall have the JACK SDK for Android, something that don't even know if it ever existed... sorry to tell... you seem to be trying to do something that is not (officially) supported: there's no JACK for Android and probably, sorry again, won't ever be...

**Comment by arun-gurung** [comment]
I changed the makefile to not use Android and use gcc, but the same error.make[1]: Entering directory `/tmp/qjackctl-git'
cd src/ && ( test -e Makefile || /opt/Qt/5.11.1/gcc_64/bin/qmake -o Makefile /tmp/qjackctl-git/src/src.pro ) && make -f Makefile
