### ISSUE TITLE
Misleading notifications

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qjackctl#45]
While checking/unckecking the new `Setup... -> Misc -> Buttons -> [] Replace Connections with Graph buttons`, we are notified that: `Server settings will be only effective after restarting the JACK audio server.`.

Despite this message, the change is made instantaneously.
This is a bit confusing from a user point of view thus there is no harm here. Only reporting it here.

HTH.

**Comment by rncbc** [comment]
mitigated by https://github.com/rncbc/qjackctl/commit/df06b2d

thanks
