### ISSUE TITLE
Can not open on Ubuntu 18.04

### ISSUE THREAD

**Issue by computersarecool** [rncbc/qjackctl#51]
Hi, I have Ubuntu 18.04 and I am trying the newest version (installing from source).

I did everything as the install said.  When I get  run `$ /usr/local/bin/qjackctl` nothing happens.  No output, nothing. Can you help me debug this somehow?

Also - have you considered making an appImage?

**Comment by rncbc** [comment]
is it the first time you're running qjackctl on that user machine?
try removing any existing  configuration file (~/.config/rncbc.org/QjackCtl.conf)
and yes there's an AppImage for this release.
cheers

**Comment by computersarecool** [comment]
I actually had the old version installed on my machine - I think from `apt` but I want the pretty new skin.
Where is the AppImage (I looked [here](https://qjackctl.sourceforge.io/#Downloads) but do not see it.)

**Comment by computersarecool** [comment]
Ah yes, deleting the existing config file helped my install (maybe should add a note about that?)

Anyway, is it possible to get the dark skin? I do not see where to enable that.
And a link to the AppImage

**Comment by computersarecool** [comment]
Thanks for the information.
