### ISSUE TITLE
Freeze during setup of dbus ?

### ISSUE THREAD

**Issue by stuaxo** [rncbc/qjackctl#56]
Hi,
   I'm trying out linux audio, jack + MIDI for the first time, and found I can get the odd freeze in QJackCTL.

Under certain circumstances, when I start up QJackCTL it has a black window.

If I kill jackdbus in the terminal `killall jackdbus -9` it carries on starting up.

Could the app continue starting up and display a message instead (or better, detect the issue and fix it) ?

**Comment by rncbc** [comment]
what do you have in the startup scripts? if anything make sure none of the commands block the startup process.

**Comment by stuaxo** [comment]
I've got 

`/usr/bin/a2jmidid –export-hw`

In the `Execute script after startup` next time I get it to happen I'll try running this.

It's might be that I'm starting more than one instance, I'm on GNOME shell and don't see a systray icon.  At the moment, I'm trying to learn a bit about MIDI, so expecting to do various strange / incorrect things :)

**Comment by rncbc** [comment]
exactly what i suspected

you forget to append the ampersand `&` to run `a2jmidid` in the background and that makes all the difference :)

`/usr/bin/a2jmidid –export-hw &`

so not a bug in qjackctl, thanks.

**Comment by stuaxo** [comment]
Ah, nice.

I wonder if the GUI could be drawn before running the script?

There could be some feedback on the GUI that the startup script is running.

**Comment by stuaxo** [comment]
Here is an mspaint mockup 
![image](https://user-images.githubusercontent.com/179677/55471571-f2cd2f00-5601-11e9-9c76-72bbb65032de.png)

**Comment by rncbc** [comment]
may i ask how could that be useful anyway?

`a2jmidid` does not ever finish to run, at least until jackd(bus) or its own process terminates or is killed explicitly.

again, as said before, make sure none of the commands do ever block on any of the pre/post startup/shutdown scripts.

you've been advised.
cheers

**Comment by stuaxo** [comment]
It would be useful, as it would give an indication of what's not configured correctly. 

Cheers for the help, I might have a look a poke at the source.

**Comment by stuaxo** [comment]
I guess in the ideal world nothing would block the UI from rendering, but I realise making all the scripts async would be a big change so won't ask for it :)
