### ISSUE TITLE
docs for session window

### ISSUE THREAD

**Issue by ensonic** [rncbc/qjackctl#58]
I am currently using 0.5.0 from debian (unstable) and try to make sense of the session window. Is there an article how this works. My intent was to add a bunch of programs (for illustration vkeybd and qsynth) to be able to launch them with one click. Ideally I would also associate a patchbay config for it to active the connections. Is that possible?

Right now I can add programs, but I am not sure how to 'activate' them?

Maybe some part of the confusion is that I am not sure why is referred to by 'Infra-Client'.

**Comment by rncbc** [comment]
there's not much of documentation on JACK session management (JSM) out there; but you can follow the following simple instructions:
0. (do this only once:) create a directory or a folder to store all your JACK sessions in the future eg.
 `mkdir -p ~/JACK_Sessions` ;
1.when everything is set up and running and sounding as you like, save the session as is: qjackctl > Session > Save...
2. in the "Save Session" dialog that follows, navigate to the "JACK_Sessions" directory (created earlier in 0.) and create a "New Folder..." under that with a name of your choice--this is the name your session, that you're saving; hit "Save" or "OK" and you're done.

if some JACK clients or program applications are not JSM-aware, which in fact might be the majority, they should be listed in the lower "Infra-clients" pane with a white-on-red-cross warning icon--these are all the client names that JSM doesn't know how to start/run but you can (and ought) to set their corresponding command line (the same one you used to start them in the first place): just click on the "Infra-command" column field and you can write that down. From that moment on, JSM will know how to start/run that client when loading the session anytime later.

I guess you're now good and ready ;)
Cheers

**Comment by ensonic** [comment]
Ahh, got it. I was manually adding 'infra-clients'. I I was wondering why thing in the upper panel changed when clicking save.
Still more questions
Q1: when I load the session, should qjackctl start the clients? I am getting these message and no qsynth showing up (and lots of red crosses in the session windows top panel).
```
Unknown source port in attempted (dis)connection src_name [qsynth:left] dst_name [system:playback_1]
qjackctlSession::update() jack_connect: "qsynth:left" => "system:playback_1" (-1)
Unknown source port in attempted (dis)connection src_name [qsynth:right] dst_name [system:playback_2]
qjackctlSession::update() jack_connect: "qsynth:right" => "system:playback_2" (-1)
Unknown source port in attempted (dis)connection src_name [qsynth:left] dst_name [system:playback_1]
qjackctlSession::update() jack_connect: "qsynth:left" => "system:playback_1" (-1)
Unknown source port in attempted (dis)connection src_name [qsynth:right] dst_name [system:playback_2]
qjackctlSession::update() jack_connect: "qsynth:right" => "system:playback_2" (-1)
```
When I manually start qsynth, it resolved.

Q2: is this jack-only? e.g. vkeyb would not be started?

**Comment by rncbc** [comment]
A1: you have to match the (infra-)client name to a command line to get it started alright; qsynth is not JSM-aware so you must provide the exact command line to run it when you load a previously saved session.

A2: JSM  is jack-only, so for alsa-midi applications you have to start them on your own.

**Comment by ensonic** [comment]
Thanks, Q1 works, but if I need to script it anyway, I can also script it to 100%. Thanks for the quick replies.
