### ISSUE TITLE
Wrong build-dependency in the Debian packaging?

### ISSUE THREAD

**Issue by trebmuh** [rncbc/qjackctl#61]
Hi Rui,

https://github.com/rncbc/qjackctl/blob/61dfaf38089fa35397f256431f2dcf5f371d99f9/debian/control#L7

It looks like there is a mistake here since there isn't such a `libjack2-dev` package on Debian's repos. It is probably `libjack-jackd2-dev` you had in mind.
_Note that there is `libjack-dev` too._

If you really want to enforce building with jack2, then a `libjack-jackd2-dev` build-depend sounds what you want here. They can be both listed in the debian/control's build-depends field with: `libjack-jackd2-dev | libjack-dev` if needed to provide alternative.

Hope that helps.

Note that the same mistake a few lines above in: `Depends: libjack2, ${shlibs:Depends}, ${misc:Depends}` which is supposed to be `Depends: jackd, ${shlibs:Depends}, ${misc:Depends}`

**Comment by rncbc** [comment]
the files under 'debian' sub-directory are for CI purposes  by OBS (openSUSE build service) eyes only :)

they are not intended to the world at large, sorry :) nor they ever appear on any release tarball for x sake.

you're of course free to change all references to `libjack2-dev` into `libjack-dev` or better yet, `libjack-jackd2-dev` (!).

**Comment by trebmuh** [comment]
OK. No worries.
