### ISSUE TITLE
Connection anomaly in graph window

### ISSUE THREAD

**Issue by jpcima** [rncbc/qjackctl#73]
I found by manipulation mistake that I can create unconnected cable items in the graph.

To create one:
1- start dragging a connection out of an output audio port of choice;
2- while it's still dragging, right-click to pop up the menu;
3- left click to make the menu go away;
4- (at this point, if you click on canvas, it would disappear and return to normal)
    start dragging a cable out of another output audio port, and drop it anywhere on canvas;
5- the situation as in the screenshot should be seen.

![Capture du 2019-10-16 18-12-58](https://user-images.githubusercontent.com/17614485/66937958-9d59ec00-f040-11e9-9055-7162d9e0d6cb.png)

6- next, try moving the client from which these cables have been pulled, and it will crash.

Qjackctl 0.5.9

**Comment by rncbc** [comment]
confirmed.
nice touch! will try to fix that before this pending release any minute or so :)
thanks && cheers

**Comment by rncbc** [comment]
hopefully fixed in https://github.com/rncbc/qjackctl/commit/cbdd11b

byee

**Comment by jpcima** [comment]
I confirm it to be fixed in the commit. I haven't noticed any adverse effect of the change after a bit of use.
Thanks !
