### ISSUE TITLE
How do I build with support for jack2 and jack1?

### ISSUE THREAD

**Issue by Jacalz** [rncbc/qjackctl#75]
When building qjackctl I have always built with jack1 because that was everything that was in the repository for my Linux distro, Solus. I manage to get Jack2 packaged but I don't know how to figure out how to build both jack1 and jack2 support. The two packages conflicts with each other so there is not possible to install them at the same time. What should I do?

**Comment by rncbc** [comment]
the JACK API is (must be) the same! so when you build qjackctl on one it will work runtime for the other as well.

however, the packaging of the development files (-dev suffix) might be different: `libjack-dev` is the most common on ubuntu/debian, but I've also seen `libjack-jackd2-dev` designated specifically for JACK2.

**Comment by Jacalz** [comment]
Yeah it does work at runtime but at build time with the cmake build system it looks like jack2 support is disabled. It made me think that building it with jack1 made it to some possible jack2 only features weren’t being built. Perhaps that should changed if that’s not the case, because for me it made a bit uncertain.

It’s this part that makes my mind think that qjackctl doesn’t build with all jack2 features:
```cmake
show_option ("  JACK Session support . . . . . . . . . . . . . . ." CONFIG_JACK_SESSION)
show_option ("  JACK Version support (JACK2) . . . . . . . . . . ." CONFIG_JACK_VERSION)
```

Perhaps it should be written in some other way to avoid any confusion?

**Comment by rncbc** [comment]
note that if you build with "JACK Version support (JACK2): yes" (eg. `./configure --enable-jack-version`..., or the equivalent `cmake -DCONFIG_JACK_VERSION`=1 ...) you'll end up with a runtime that only works on JACK2.

you better not take that option as it's quite irrelevant for qjackctl function: it just serves the current JACK2 version string in the about box and nothing else :)

**Comment by Jacalz** [comment]
Thanks for the clarification and thanks for making great software 👍
