### ISSUE TITLE
Dummy driver looks to be sent traslated

### ISSUE THREAD

**Issue by vallsv** [rncbc/qjackctl#81]
Hi,

I am using qjackctl 0.5.0.

I am trying to run the dummy driver using the GUI. This driver is translated in the selection widget. In french `dummy` is translated to `factice`.

Then when i start the server, `jackd` looks to fail cause `factice` is unknown. I guess `dummy` is expected here.

```
20:19:43.038 /usr/bin/jackd -r -dfactice -r44100 -p1024
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=Aucun fichier ou dossier de ce type)
attempt to connect to server failed
jackd 0.125.0rc1
Copyright 2001-2009 Paul Davis, Stephane Letz, Jack O'Quinn, Torben Hohn and others.
jackd comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
jackd: unknown driver 'factice'
no message buffer overruns
```

**Comment by trebmuh** [comment]
Please, use a [more recent](https://github.com/rncbc/qjackctl/releases) version of QjackCtl where [it isn't translated anymore](https://github.com/rncbc/qjackctl/blob/master/src/translations/qjackctl_fr.ts#L2888).

**Comment by vallsv** [comment]
I am using the version from the last Ubuntu (then i guess Debian 10).
But If it is already fixed, it's fine.
Regards,
