### ISSUE TITLE
[PATCH] qjackctl doesn't start jack on macos, and sets default driver to alsa. 

### ISSUE THREAD

**Issue by kmatheussen** [rncbc/qjackctl#82]
Hi, here's a couple of quick, but important, fixes for macos. Hope it's okay I didn't make a pull request since I've cloned qjackctl a long time ago and don't want to mess with git: https://raw.githubusercontent.com/kmatheussen/qjackctl_macos/master/qjackctl.diff

Also, here's a repository to build qjackctl 0.6.0 for macos: https://github.com/kmatheussen/qjackctl_macos

**Comment by rncbc** [comment]
patch applied as https://github.com/rncbc/qjackctl/commit/aa03b64

thanks
