### ISSUE TITLE
[feature-request] Use jack_property for renaming ports

### ISSUE THREAD

**Issue by mxa** [rncbc/qjackctl#85]
It's cool that in the Graph window one can rename the ports by double clicking on it or rightclick, Rename.
It would be even greater if the new name would be reflected elsewhere too. Renaming in the Graph could actually run jack_property to change the port [metadata](https://jackaudio.org/metadata/).

**Comment by rncbc** [comment]
it's been already there since inception of the Graph as is on the Connections for ages.
it needs you to enable the proper option though (Setup > Display > Connections > Enable

**Comment by mxa** [comment]
hm, that was enabled, but I can't see the in Graph renamed ports in other jack clients like patchage.

**Comment by rncbc** [comment]
patchage or any other jack-client has to have support for pretty-names metadata, of course.
