### ISSUE TITLE
False Positive Realtime Flag in Messages-Status

### ISSUE THREAD

**Issue by diovudau** [rncbc/qjackctl#86]
I set up a new operating system.(Archlinux)
After installing jack2  `jackdmp version 1.9.14` and qjackctl `0.6.1`, but without confiuring the system for realtime, I started jack, just for fun.

The message log said RT was not possibly, as expected. 
Jack started anyway and Qjackctls info in the Messages window, Status tab said "Realtime Mode: yes". Which was obviously not true.

Information-feedback to the (inexperienced) user is very important. We need to be able to trust the programs.
Could you look into that please and make sure it is reporting the correct values.

**Comment by rncbc** [comment]
one thing is your system being setup and configured for proper realtime operation (kernel, permissions, scheduling priorities limits, etc.); most important and here a must do is having the user on audio group and configuring its PAM /etc/security/limits.conf correctly.

one other thing, very different in nature, is the JACK server running in the so called real-time mode--this being reported on the Messages/Status tab for sure (also on main display panel, a blinking RT indicator).

for the latter to run smoothly it surely needs the former, but not quite necessary or the same thing.
