### ISSUE TITLE
Rubber band selection in graph window

### ISSUE THREAD

**Issue by mxa** [rncbc/qjackctl#87]
In the graph window, it's totally possible to shift-select multiple items and subsequently move them as a group. Strangely when using the rubber band method to select multiple items it's not possible to move them together.

**Comment by rncbc** [comment]
you can only drag-move group selections when you get whole nodes (ie. clients) and not any of their own ports selected--that is when selecting on a rubber-band (or lasso) make sure you don't hit any port or connection line _inside_ that rectangle.
hth.
cheers

**Comment by mxa** [comment]
AAh I see. It's a bit confusing since the ports are also selected when just selecting the rectangle. So visually it's the same if only the rectangle is selected or the rectangle with its ports is selected.

**Comment by rncbc** [comment]
yes you're right, however, the rule applies to drag-moving one or more nodes together; the way that all ports in a node is also selected stands for other purposes not related to moving them around eg. making some full connections and disconnections, etc.
