### ISSUE TITLE
Option to Ignore All Self Connect Requests

### ISSUE THREAD

**Issue by mikeperalta1** [rncbc/qjackctl#89]
Hi friends,
One of the dealbreakers preventing me from switching to QJackCtl is there is no option to ignore "self connect requests".
Sometimes I need to restart the engine, and when that happens, there appears to be some sort of request by jack (or the hardware; not sure) to set up initial connections.
But when this happens, it messes up all the work I've done setting up connections the way I prefer. I must then select all, disconnect all, then reload my saved connections.
It's a minor inconvenience but still several clicks extra work, which I'm sure is maddening to newbies (it was to me before I realized what was happening).

As an example, here's a screenshot of the tool I currently use: Claudia:
![image](https://user-images.githubusercontent.com/26490778/78840903-e3b95380-79b0-11ea-8075-a2598a47ba23.png)

When I select that option "Ignore all self-connect requests", no additional connections are ever made just because I restart jack or other modules. Thus, when my DAW comes back up, my previous connection state reappears instantly.

**Comment by mikeperalta1** [comment]
Just some more information. It seems this setting effectively changes configuration of jack for the following setting in ~/.config/jack/conf.xml

```xml
<option name="self-connect-mode">a</option>
```

The "a" value for this option seems to be what does the trick.

Without that setting, here's a visualization of what happens after I restart jack:
![image](https://user-images.githubusercontent.com/26490778/78841652-c71e1b00-79b2-11ea-919f-b03736bb755d.png)
Notice all the extra connections happening between the system, sinks, and sources.

Just to contrast, this is what I setup+save, and expect:
![image](https://user-images.githubusercontent.com/26490778/78841691-e321bc80-79b2-11ea-9169-0c72506e2da7.png)

**Comment by rncbc** [comment]
if you can set that option for good in the jackdbus configuration file (possibly via `jack_control`) why should it be included in qjackctl ?

also, the situation you seem to have in your example is due to auto-connection within the pulseadio/jack modules specifically--why don't you tacle that instead?

personally, i don't really get the point of that "restrict selt-connections" option anyway: why on earth jack applications cannot make their own connections on their own premises and interest? though i reckon the emergence of it on a (old? dead? niche?) LADISH context. but no, I still don't get it, sorry.

**Comment by mikeperalta1** [comment]
Look at it from the new user's perspective. Not an advanced user who can go under the hood, or knows many other tools. A new linux audio user starting with qjackctl will most likely open the settings menu and see that qjackctl seems to claim to configure jack properly. Then, the apparent default behavior of auto connecting will be maddening, as qjackctl has many options but doesn't have one to address the issue, nor any explanation of what is causing the behavior. After a lot of wasted time and frustration, the assumption will be that something is wrong with qjackctl and the user will move on. Eventually, after trying other tools, the user may realize the problem is only half qjackctl; Not that qjackctl is causing auto connections, but that its jack configuration dialog is missing options to ignore auto connection requests (perhaps even with an extra tooltip explaining jack modules likely have a setting for autoconnect that can be addressed).

I think it's intuitive to include important options and hints in a control panel that configures a tool, if the goal is to capture and be useful to as many users as possible (taking into account varying levels of skill). Otherwise the question is: Why put *any* option in there at all?

As for why I couldn't tackle auto-connection directly myself. I did, by switching to Claudia. It is much easier to use a tool that makes important configuration easy. Sure, I could have spent the time to research how to deal with this issue myself, with my own custom scripts or whatnot. I tried a few times before and failed though. How many more users left that way?

Maybe I should ask: Is the point/mission of qjackctl to be the one tool you use to configure/manage jack, or is there an expectation that other jack management tools (like Claudia) would be used alongside it?

Just as an aside so you can lol @ me a little, and to really emphasize the benefit of a configuration tool being as helpful/intuitive as possible: It wasn't until you mentioned "also, the situation you seem to have in your example is due to auto-connection within the pulseadio/jack modules specifically--why don't you tacle that instead?" that I looked at my screenshot a second time and finally realized the system connections weren't auto-connecting. I then went back to https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-jack-sink to see there was a boolean "connect" argument when adding these modules. I'm no expert, but I've written scripts to setup these connections on at least 3 machines.... and still didn't realize until your hint. Isn't it possible the average user might have this problem, too?

For now, I'm going to modify my scripts and see if I can use qjackctl again. It is a nice little tool.

**Comment by Gooberpatrol66** [comment]
Where did you find documentation for this? What letter do I put for "ignore for external ports only"?

**Comment by Gooberpatrol66** [comment]
Actually, I can't get this to work at all; it still autoconnects.

**Comment by mikeperalta1** [comment]
Yeah after I wrote that comment I tried several tests and couldn't get the jack module to stop auto-connecting either. For now I have to continue using Claudia.

**Comment by rncbc** [comment]
finally indulged in https://github.com/rncbc/qjackctl/commit/6821fe0 ;)

cheers

**Comment by mikeperalta1** [comment]
How cool and thank you. I can't wait to try out qjackctl again!
