### ISSUE TITLE
Can't remove shiny glass light effect

### ISSUE THREAD

**Issue by jameh** [rncbc/qjackctl#93]
Before this commit e73ae26512f6f978b08d3ceabc1c2ca69dab8bff, this was an option.

Can we have this as an option again?

![2020-04-30-011722_487x135_scrot](https://user-images.githubusercontent.com/1538657/80693160-78cadc00-8a87-11ea-81b1-59868780fdd4.png)

**Comment by rncbc** [comment]
nope. 

but you can still turn it off on the configuration file (`~/.config/rncbc.org/QjackCtl.conf`):
```
[Options]
DisplayEffect=false
```
hth
cheers

**Comment by jameh** [comment]
good enough for me :+1:

**Comment by mark-orion** [comment]
I know this is closed but I really do not see any advantage of this shiny display effect. A studio setup needs to be easily readable - almost like a cockpit. Introducing artificial glare is the last thing one wants. I would highly recommend to either re-introduce an option to disable this in the gui or to have it off by default.

**Comment by rncbc** [comment]
@mark-orion : please read https://github.com/rncbc/qjackctl/issues/93#issuecomment-621780215

**Comment by yaxu** [comment]
@mark-orion Agreed, it should be default off. How could anyone look at the above screenshot and think it was a good idea?
